import localFont from 'next/font/local'
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const technor = localFont({
  src: '../public/fonts/Technor-Variable.woff2',
  variable: '--font-technor'
})

const supreme = localFont({
  src: [
    {
      path: '../public/fonts/Supreme-Variable.woff2',
      style: 'normal'
    },
    {
      path: '../public/fonts/Supreme-VariableItalic.woff2',
      style: 'italic'
    }
  ],
  variable: '--font-supreme'
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${technor.variable} ${supreme.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
